version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "21:00"
  open-pull-requests-limit: 10
  versioning-strategy: increase
  ignore:
  - dependency-name: webpack
    versions:
    - 5.21.2
    - 5.22.0
    - 5.23.0
    - 5.24.0
    - 5.24.3
    - 5.24.4
    - 5.25.0
    - 5.26.0
    - 5.26.2
    - 5.26.3
    - 5.27.0
    - 5.27.2
    - 5.28.0
    - 5.30.0
    - 5.31.0
    - 5.31.2
    - 5.32.0
    - 5.33.2
    - 5.35.0
    - 5.35.1
    - 5.36.0
  - dependency-name: "@types/node"
    versions:
    - 14.14.26
    - 14.14.27
    - 14.14.28
    - 14.14.29
    - 14.14.31
    - 14.14.32
    - 14.14.33
    - 14.14.34
    - 14.14.35
    - 14.14.36
    - 14.14.37
    - 14.14.39
    - 14.14.41
    - 15.0.0
  - dependency-name: ts-loader
    versions:
    - 8.0.16
    - 8.0.17
    - 8.0.18
    - 8.1.0
    - 8.2.0
    - 9.0.2
    - 9.1.0
  - dependency-name: rollup
    versions:
    - 2.39.0
    - 2.39.1
    - 2.40.0
    - 2.41.0
    - 2.41.1
    - 2.41.2
    - 2.41.4
    - 2.41.5
    - 2.42.0
    - 2.42.3
    - 2.42.4
    - 2.44.0
    - 2.45.0
    - 2.45.1
  - dependency-name: "@typescript-eslint/eslint-plugin"
    versions:
    - 4.15.0
    - 4.15.1
    - 4.15.2
    - 4.16.1
    - 4.17.0
    - 4.18.0
    - 4.19.0
    - 4.20.0
    - 4.21.0
  - dependency-name: "@typescript-eslint/parser"
    versions:
    - 4.15.0
    - 4.15.1
    - 4.15.2
    - 4.16.1
    - 4.17.0
    - 4.18.0
    - 4.19.0
    - 4.20.0
    - 4.21.0
  - dependency-name: y18n
    versions:
    - 4.0.1
  - dependency-name: husky
    versions:
    - 5.0.9
    - 5.1.1
    - 5.1.2
    - 5.1.3
    - 5.2.0
  - dependency-name: html-webpack-plugin
    versions:
    - 5.1.0
    - 5.2.0
    - 5.3.0
  - dependency-name: typescript
    versions:
    - 4.1.4
    - 4.1.5
    - 4.2.2
  - dependency-name: eslint-plugin-sonarjs
    versions:
    - 0.6.0
